apiVersion: v1
kind: ConfigMap
metadata:
  name: rpc
data:
  bitcoin: "bitcoin-rpc.publicnode.com"
  ethereum: "https://ethereum-rpc.publicnode.com"
  arbitrum: "https://arbitrum-rpc.publicnode.com"
  avalanche: "https://avalanche-c-chain-rpc.publicnode.com"
  bsc: "https://bsc-rpc.publicnode.com"
  base: "https://base-rpc.publicnode.com"
  blast: "https://blast-rpc.publicnode.com"
  optimism: "https://optimism-rpc.publicnode.com"
  polygon: "https://polygon-bor-rpc.publicnode.com"
