apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-indexer
  labels:
    app: tx-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-indexer
  template:
    metadata:
      labels:
        app: tx-indexer
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: tx-indexer
          image: busybox
          command: ["/app/main"]
          ports:
            - containerPort: 80
              name: health
          env:
            - name: HEALTHPORT
              value: "80"
            - name: BASE_RPC_ETHEREUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: ethereum
            - name: BASE_RPC_BITCOIN_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: bitcoin
            - name: BASE_INTERVAL
              value: "30s"
            - name: BASE_ITERATIONTIMEOUT
              value: "30s"
            - name: BASE_MARKLOSTAFTER
              value: "2h"
            - name: BASE_CONCURRENCY
              value: "5"
            - name: BASE_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
