apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: egress
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: proxy
          image: mitmproxy/mitmproxy:12.2.0
          args:
            - mitmdump
            - --mode
            - regular
            - --listen-port
            - "3128"
            - --listen-host
            - 0.0.0.0
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          resources:
            requests:
              cpu: 256m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: egress
spec:
  selector:
    app: proxy
  ports:
    - name: http
      port: 3128
      targetPort: 3128
      protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-proxy
  namespace: egress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-proxy
  namespace: egress
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: proxy
